name: my_app
description: Una nueva app Flutter con patrón BLoC
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.3
  shared_preferences: ^2.5.3

  # Firebase
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  firebase_storage: ^13.0.1
  get_it: ^8.2.0
  dartz: ^0.10.1
  syncfusion_flutter_pdfviewer: ^31.1.21
  syncfusion_flutter_pdf: ^31.1.21
  adaptive_theme: ^3.7.1+2
  visibility_detector: ^0.4.0+2
  cached_network_image: ^3.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
